spring.application.name=Authorization-Registration-Client
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/KeyCloackTest
spring.security.oauth2.client.registration.keycloak.client-id=myuser
spring.security.oauth2.client.registration.keycloak.client-secret=1
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9090/realms/KeyCloackTest
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

logging.level.org.springframework.security=TRACE

#spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID
#spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET
#spring.security.oauth2.client.registration.google.scope=email,profile
#
#spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com
