spring.application.name=Authorization-Registration-Client
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/KeyCloackTest
spring.security.oauth2.client.registration.keycloak.client-id=myuser
spring.security.oauth2.client.registration.keycloak.client-secret=C9M6cWOufPNrBMk4uBwEZUBsv867ZKle
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9090/realms/KeyCloackTest
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

logging.level.org.springframework.security=TRACE

#spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID
#spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET
#spring.security.oauth2.client.registration.google.scope=email,profile
#
#spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com
#{
#"exp": 1774963633,
#"iat": 1774963333,
#"jti": "onrtro:5f0c2495-c91c-6ecb-94e7-ec275e23e4d0",
#"iss": "http://192.168.10.87:9090/realms/KeyCloackTest",
#"aud": "account",
#"sub": "8813e303-2843-4031-8428-fc39e5fbc98d",
#"typ": "Bearer",
#"azp": "myuser",
#"sid": "REafNlWq3MYnJLT6gzWEduRN",
#"acr": "1",
#"allowed-origins": [
#"http://192.168.10.87:8080"
#],
#"realm_access": {
#"roles": [
#"default-roles-keycloacktest",
#"offline_access",
#"uma_authorization"
#]
#},
#"resource_access": {
#"account": {
#"roles": [
#"manage-account",
#"manage-account-links",
#"view-profile"
#]
#}
#},
#"scope": "email profile",
#"email_verified": false,
#"name": "14 15",
#"preferred_username": "goon@gmail.com",
#"given_name": "14",
#"family_name": "15",
#"email": "goon@gmail.com"
#} ????? ?????????? ???